version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: fluxo-postgres
    environment:
      POSTGRES_DB: fluxoalfa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fluxoalfa"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fluxo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: fluxo-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  user-frontend:
    build:
      context: .
      dockerfile: ./apps/user-frontend/Dockerfile
    container_name: fluxo-user-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${BACKEND_URL:-http://localhost:8000}

  admin-frontend:
    build:
      context: .
      dockerfile: ./apps/admin-frontend/Dockerfile
    container_name: fluxo-admin-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${BACKEND_URL:-http://localhost:8000}

volumes:
  postgres_data:
  redis_data: